services:
  - type: web
    name: frappedollars-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host=0.0.0.0 --port=$PORT
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        value: https://lllkrhivavsujgcfhcls.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_SA2ex7Iy0bUPvowzcHyJNg_e5EPBdiH
      - key: ADMIN_API_KEY
        value: a23112857d84806ef3201f526ea2558a
      - key: PYTHONPATH
        value: .