// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUKRLniu0ndndxYGyt8JtU2UtImH52FFE',
    appId: '1:460271892368:web:98f3b8aa9e19cc0962a515',
    messagingSenderId: '460271892368',
    projectId: 'frappe-dollars',
    authDomain: 'frappe-dollars.firebaseapp.com',
    storageBucket: 'frappe-dollars.firebasestorage.app',
    measurementId: 'G-VNVES3ZVGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3ti0P37xJ3f-vwYQWEsc0vECJYeM0rU',
    appId: '1:460271892368:android:74664ac04bbf13d662a515',
    messagingSenderId: '460271892368',
    projectId: 'frappe-dollars',
    storageBucket: 'frappe-dollars.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhpu9bqS0cQMJ6IBaEzA46Gvcr7nEFQM',
    appId: '1:460271892368:ios:4cad95a57e3288a562a515',
    messagingSenderId: '460271892368',
    projectId: 'frappe-dollars',
    storageBucket: 'frappe-dollars.firebasestorage.app',
    iosBundleId: 'com.example.frappedollars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhpu9bqS0cQMJ6IBaEzA46Gvcr7nEFQM',
    appId: '1:460271892368:ios:4cad95a57e3288a562a515',
    messagingSenderId: '460271892368',
    projectId: 'frappe-dollars',
    storageBucket: 'frappe-dollars.firebasestorage.app',
    iosBundleId: 'com.example.frappedollars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUKRLniu0ndndxYGyt8JtU2UtImH52FFE',
    appId: '1:460271892368:web:7bf43ba4e86a96d162a515',
    messagingSenderId: '460271892368',
    projectId: 'frappe-dollars',
    authDomain: 'frappe-dollars.firebaseapp.com',
    storageBucket: 'frappe-dollars.firebasestorage.app',
    measurementId: 'G-XV08EE80TD',
  );
}
